language: cpp
matrix:
  include:
    - os: linux
      dist: xenial
      env: TOOL=clang-format
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-7
          packages:
            - clang-format-7
      compiler: clang
    - os: osx
      osx_image: xcode10.2
      env: TOOL=test
    - os: linux
      dist: xenial
      env: TOOL=test
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - g++-8
            - cmake
            - libboost-system1.58-dev
            - libboost-filesystem1.58-dev
            - libboost-test1.58-dev
            - libboost-program-options1.58-dev
    - os: linux
      dist: xenial
      env: TOOL=doxygen
      addons:
        apt:
          packages:
            - doxygen
            - doxygen-doc
            - doxygen-latex
            - doxygen-gui
            - graphviz
            - cmake
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_API_TOKEN
        local_dir: build/doc/html
        on:
          branch: dev
before_install:
  - if [[ $TOOL == "test" ]]; then git clone https://github.com/oliora/ppconsul.git; mkdir ppconsul_install; mkdir ppconsul/build; fi
install:
  - if [[ $TOOL == "test" ]]; then cd ppconsul/build; fi
  - if [[ $TOOL == "test" ]]; then cmake .. -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/ppconsul_install && make -j install; fi
  - if [[ $TOOL == "test" ]]; then cd $TRAVIS_BUILD_DIR; fi
before_script: 
  - if [[ $TOOL == "test" ]]; then mkdir build; cd build; fi
script:
  - if [[ $TOOL == "test" ]] && [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake .. -Dppconsul_DIR=$TRAVIS_BUILD_DIR/ppconsul_install/cmake -DCMAKE_C_COMPILER=/usr/bin/gcc-8 -DCMAKE_CXX_COMPILER=/usr/bin/g++-8; fi
  - if [[ $TOOL == "test" ]] && [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake .. -Dppconsul_DIR=$TRAVIS_BUILD_DIR/ppconsul_install/cmake; fi
  - if [[ $TOOL == "test" ]]; then make -j; fi
  - if [[ $TOOL == "test" && "$TRAVIS_OS_NAME" == "linux" ]]; then make test; fi
  - if [[ $TOOL == "doxygen" ]]; then cmake ..; make doc; fi
  - if [[ $TOOL == "clang-format" ]] && [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
      cd $TRAVIS_BUILD_DIR;
      BASE_COMMIT=$(git rev-parse $TRAVIS_BRANCH);
      COMMIT_FILES=$(git diff --name-only $BASE_COMMIT | grep -i -v LinkDef);
      RESULT_OUTPUT="$(git-clang-format-7 --commit $BASE_COMMIT --diff --binary `which clang-format-7` $COMMIT_FILES)";
      if [ "$RESULT_OUTPUT" == "no modified files to format" ] || [ "$RESULT_OUTPUT" == "clang-format did not modify any files" ]; then
        echo "clang-format passed";
        exit 0;
      else
        echo "clang-format failed.";
        echo "$RESULT_OUTPUT";
        exit 1;
      fi
    fi
notifications:
  email: false
