// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/http.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "google/api/http.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace google {
namespace api {

namespace {

const ::google::protobuf::Descriptor* Http_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Http_reflection_ = NULL;
const ::google::protobuf::Descriptor* HttpRule_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  HttpRule_reflection_ = NULL;
struct HttpRuleOneofInstance {
  ::google::protobuf::internal::ArenaStringPtr get_;
  ::google::protobuf::internal::ArenaStringPtr put_;
  ::google::protobuf::internal::ArenaStringPtr post_;
  ::google::protobuf::internal::ArenaStringPtr delete__;
  ::google::protobuf::internal::ArenaStringPtr patch_;
  const ::google::api::CustomHttpPattern* custom_;
}* HttpRule_default_oneof_instance_ = NULL;
const ::google::protobuf::Descriptor* CustomHttpPattern_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CustomHttpPattern_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_google_2fapi_2fhttp_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_google_2fapi_2fhttp_2eproto() {
  protobuf_AddDesc_google_2fapi_2fhttp_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "google/api/http.proto");
  GOOGLE_CHECK(file != NULL);
  Http_descriptor_ = file->message_type(0);
  static const int Http_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Http, rules_),
  };
  Http_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Http_descriptor_,
      Http::default_instance_,
      Http_offsets_,
      -1,
      -1,
      -1,
      sizeof(Http),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Http, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Http, _is_default_instance_));
  HttpRule_descriptor_ = file->message_type(1);
  static const int HttpRule_offsets_[10] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HttpRule, selector_),
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(HttpRule_default_oneof_instance_, get_),
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(HttpRule_default_oneof_instance_, put_),
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(HttpRule_default_oneof_instance_, post_),
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(HttpRule_default_oneof_instance_, delete__),
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(HttpRule_default_oneof_instance_, patch_),
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(HttpRule_default_oneof_instance_, custom_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HttpRule, body_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HttpRule, additional_bindings_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HttpRule, pattern_),
  };
  HttpRule_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      HttpRule_descriptor_,
      HttpRule::default_instance_,
      HttpRule_offsets_,
      -1,
      -1,
      -1,
      HttpRule_default_oneof_instance_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HttpRule, _oneof_case_[0]),
      sizeof(HttpRule),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HttpRule, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HttpRule, _is_default_instance_));
  CustomHttpPattern_descriptor_ = file->message_type(2);
  static const int CustomHttpPattern_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CustomHttpPattern, kind_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CustomHttpPattern, path_),
  };
  CustomHttpPattern_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      CustomHttpPattern_descriptor_,
      CustomHttpPattern::default_instance_,
      CustomHttpPattern_offsets_,
      -1,
      -1,
      -1,
      sizeof(CustomHttpPattern),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CustomHttpPattern, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CustomHttpPattern, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_google_2fapi_2fhttp_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Http_descriptor_, &Http::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      HttpRule_descriptor_, &HttpRule::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      CustomHttpPattern_descriptor_, &CustomHttpPattern::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_google_2fapi_2fhttp_2eproto() {
  delete Http::default_instance_;
  delete Http_reflection_;
  delete HttpRule::default_instance_;
  delete HttpRule_default_oneof_instance_;
  delete HttpRule_reflection_;
  delete CustomHttpPattern::default_instance_;
  delete CustomHttpPattern_reflection_;
}

void protobuf_AddDesc_google_2fapi_2fhttp_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_google_2fapi_2fhttp_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\025google/api/http.proto\022\ngoogle.api\"+\n\004H"
    "ttp\022#\n\005rules\030\001 \003(\0132\024.google.api.HttpRule"
    "\"\352\001\n\010HttpRule\022\020\n\010selector\030\001 \001(\t\022\r\n\003get\030\002"
    " \001(\tH\000\022\r\n\003put\030\003 \001(\tH\000\022\016\n\004post\030\004 \001(\tH\000\022\020\n"
    "\006delete\030\005 \001(\tH\000\022\017\n\005patch\030\006 \001(\tH\000\022/\n\006cust"
    "om\030\010 \001(\0132\035.google.api.CustomHttpPatternH"
    "\000\022\014\n\004body\030\007 \001(\t\0221\n\023additional_bindings\030\013"
    " \003(\0132\024.google.api.HttpRuleB\t\n\007pattern\"/\n"
    "\021CustomHttpPattern\022\014\n\004kind\030\001 \001(\t\022\014\n\004path"
    "\030\002 \001(\tB\'\n\016com.google.apiB\tHttpProtoP\001\370\001\001"
    "\242\002\004GAPIb\006proto3", 415);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "google/api/http.proto", &protobuf_RegisterTypes);
  Http::default_instance_ = new Http();
  HttpRule::default_instance_ = new HttpRule();
  HttpRule_default_oneof_instance_ = new HttpRuleOneofInstance();
  CustomHttpPattern::default_instance_ = new CustomHttpPattern();
  Http::default_instance_->InitAsDefaultInstance();
  HttpRule::default_instance_->InitAsDefaultInstance();
  CustomHttpPattern::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_google_2fapi_2fhttp_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_google_2fapi_2fhttp_2eproto {
  StaticDescriptorInitializer_google_2fapi_2fhttp_2eproto() {
    protobuf_AddDesc_google_2fapi_2fhttp_2eproto();
  }
} static_descriptor_initializer_google_2fapi_2fhttp_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Http::kRulesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Http::Http()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:google.api.Http)
}

Http::Http(::google::protobuf::Arena* arena)
  : ::google::protobuf::Message(),
  _internal_metadata_(arena),
  rules_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:google.api.Http)
}

void Http::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Http::Http(const Http& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:google.api.Http)
}

void Http::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
}

Http::~Http() {
  // @@protoc_insertion_point(destructor:google.api.Http)
  SharedDtor();
}

void Http::SharedDtor() {
  if (GetArenaNoVirtual() != NULL) {
    return;
  }

  if (this != default_instance_) {
  }
}

void Http::ArenaDtor(void* object) {
  Http* _this = reinterpret_cast< Http* >(object);
  (void)_this;
}
void Http::RegisterArenaDtor(::google::protobuf::Arena* arena) {
}
void Http::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Http::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Http_descriptor_;
}

const Http& Http::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_google_2fapi_2fhttp_2eproto();
  return *default_instance_;
}

Http* Http::default_instance_ = NULL;

Http* Http::New(::google::protobuf::Arena* arena) const {
  return ::google::protobuf::Arena::CreateMessage<Http>(arena);
}

void Http::Clear() {
// @@protoc_insertion_point(message_clear_start:google.api.Http)
  rules_.Clear();
}

bool Http::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:google.api.Http)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .google.api.HttpRule rules = 1;
      case 1: {
        if (tag == 10) {
          DO_(input->IncrementRecursionDepth());
         parse_loop_rules:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_rules()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_loop_rules;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:google.api.Http)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:google.api.Http)
  return false;
#undef DO_
}

void Http::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:google.api.Http)
  // repeated .google.api.HttpRule rules = 1;
  for (unsigned int i = 0, n = this->rules_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->rules(i), output);
  }

  // @@protoc_insertion_point(serialize_end:google.api.Http)
}

::google::protobuf::uint8* Http::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:google.api.Http)
  // repeated .google.api.HttpRule rules = 1;
  for (unsigned int i = 0, n = this->rules_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, this->rules(i), false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:google.api.Http)
  return target;
}

int Http::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:google.api.Http)
  int total_size = 0;

  // repeated .google.api.HttpRule rules = 1;
  total_size += 1 * this->rules_size();
  for (int i = 0; i < this->rules_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->rules(i));
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Http::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:google.api.Http)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Http* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Http>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:google.api.Http)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:google.api.Http)
    MergeFrom(*source);
  }
}

void Http::MergeFrom(const Http& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:google.api.Http)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  rules_.MergeFrom(from.rules_);
}

void Http::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:google.api.Http)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Http::CopyFrom(const Http& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.api.Http)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Http::IsInitialized() const {

  return true;
}

void Http::Swap(Http* other) {
  if (other == this) return;
  if (GetArenaNoVirtual() == other->GetArenaNoVirtual()) {
    InternalSwap(other);
  } else {
    Http temp;
    temp.MergeFrom(*this);
    CopyFrom(*other);
    other->CopyFrom(temp);
  }
}
void Http::UnsafeArenaSwap(Http* other) {
  if (other == this) return;
  GOOGLE_DCHECK(GetArenaNoVirtual() == other->GetArenaNoVirtual());
  InternalSwap(other);
}
void Http::InternalSwap(Http* other) {
  rules_.UnsafeArenaSwap(&other->rules_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Http::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Http_descriptor_;
  metadata.reflection = Http_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Http

// repeated .google.api.HttpRule rules = 1;
int Http::rules_size() const {
  return rules_.size();
}
void Http::clear_rules() {
  rules_.Clear();
}
const ::google::api::HttpRule& Http::rules(int index) const {
  // @@protoc_insertion_point(field_get:google.api.Http.rules)
  return rules_.Get(index);
}
::google::api::HttpRule* Http::mutable_rules(int index) {
  // @@protoc_insertion_point(field_mutable:google.api.Http.rules)
  return rules_.Mutable(index);
}
::google::api::HttpRule* Http::add_rules() {
  // @@protoc_insertion_point(field_add:google.api.Http.rules)
  return rules_.Add();
}
::google::protobuf::RepeatedPtrField< ::google::api::HttpRule >*
Http::mutable_rules() {
  // @@protoc_insertion_point(field_mutable_list:google.api.Http.rules)
  return &rules_;
}
const ::google::protobuf::RepeatedPtrField< ::google::api::HttpRule >&
Http::rules() const {
  // @@protoc_insertion_point(field_list:google.api.Http.rules)
  return rules_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int HttpRule::kSelectorFieldNumber;
const int HttpRule::kGetFieldNumber;
const int HttpRule::kPutFieldNumber;
const int HttpRule::kPostFieldNumber;
const int HttpRule::kDeleteFieldNumber;
const int HttpRule::kPatchFieldNumber;
const int HttpRule::kCustomFieldNumber;
const int HttpRule::kBodyFieldNumber;
const int HttpRule::kAdditionalBindingsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

HttpRule::HttpRule()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:google.api.HttpRule)
}

HttpRule::HttpRule(::google::protobuf::Arena* arena)
  : ::google::protobuf::Message(),
  _internal_metadata_(arena),
  additional_bindings_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:google.api.HttpRule)
}

void HttpRule::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  HttpRule_default_oneof_instance_->get_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  HttpRule_default_oneof_instance_->put_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  HttpRule_default_oneof_instance_->post_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  HttpRule_default_oneof_instance_->delete__.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  HttpRule_default_oneof_instance_->patch_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  HttpRule_default_oneof_instance_->custom_ = const_cast< ::google::api::CustomHttpPattern*>(&::google::api::CustomHttpPattern::default_instance());
}

HttpRule::HttpRule(const HttpRule& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:google.api.HttpRule)
}

void HttpRule::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  selector_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  body_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_pattern();
}

HttpRule::~HttpRule() {
  // @@protoc_insertion_point(destructor:google.api.HttpRule)
  SharedDtor();
}

void HttpRule::SharedDtor() {
  if (GetArenaNoVirtual() != NULL) {
    return;
  }

  selector_.Destroy(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
  body_.Destroy(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
  if (has_pattern()) {
    clear_pattern();
  }
  if (this != default_instance_) {
  }
}

void HttpRule::ArenaDtor(void* object) {
  HttpRule* _this = reinterpret_cast< HttpRule* >(object);
  (void)_this;
}
void HttpRule::RegisterArenaDtor(::google::protobuf::Arena* arena) {
}
void HttpRule::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* HttpRule::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return HttpRule_descriptor_;
}

const HttpRule& HttpRule::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_google_2fapi_2fhttp_2eproto();
  return *default_instance_;
}

HttpRule* HttpRule::default_instance_ = NULL;

HttpRule* HttpRule::New(::google::protobuf::Arena* arena) const {
  return ::google::protobuf::Arena::CreateMessage<HttpRule>(arena);
}

void HttpRule::clear_pattern() {
// @@protoc_insertion_point(one_of_clear_start:google.api.HttpRule)
  switch(pattern_case()) {
    case kGet: {
      pattern_.get_.Destroy(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
          GetArenaNoVirtual());
      break;
    }
    case kPut: {
      pattern_.put_.Destroy(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
          GetArenaNoVirtual());
      break;
    }
    case kPost: {
      pattern_.post_.Destroy(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
          GetArenaNoVirtual());
      break;
    }
    case kDelete: {
      pattern_.delete__.Destroy(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
          GetArenaNoVirtual());
      break;
    }
    case kPatch: {
      pattern_.patch_.Destroy(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
          GetArenaNoVirtual());
      break;
    }
    case kCustom: {
      if (GetArenaNoVirtual() == NULL) {
        delete pattern_.custom_;
      }
      break;
    }
    case PATTERN_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = PATTERN_NOT_SET;
}


void HttpRule::Clear() {
// @@protoc_insertion_point(message_clear_start:google.api.HttpRule)
  selector_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
  body_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
  additional_bindings_.Clear();
  clear_pattern();
}

bool HttpRule::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:google.api.HttpRule)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string selector = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_selector()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->selector().data(), this->selector().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.api.HttpRule.selector"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_get;
        break;
      }

      // optional string get = 2;
      case 2: {
        if (tag == 18) {
         parse_get:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_get()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->get().data(), this->get().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.api.HttpRule.get"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_put;
        break;
      }

      // optional string put = 3;
      case 3: {
        if (tag == 26) {
         parse_put:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_put()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->put().data(), this->put().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.api.HttpRule.put"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_post;
        break;
      }

      // optional string post = 4;
      case 4: {
        if (tag == 34) {
         parse_post:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_post()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->post().data(), this->post().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.api.HttpRule.post"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_delete;
        break;
      }

      // optional string delete = 5;
      case 5: {
        if (tag == 42) {
         parse_delete:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_delete_()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->delete_().data(), this->delete_().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.api.HttpRule.delete"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(50)) goto parse_patch;
        break;
      }

      // optional string patch = 6;
      case 6: {
        if (tag == 50) {
         parse_patch:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_patch()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->patch().data(), this->patch().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.api.HttpRule.patch"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(58)) goto parse_body;
        break;
      }

      // optional string body = 7;
      case 7: {
        if (tag == 58) {
         parse_body:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_body()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->body().data(), this->body().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.api.HttpRule.body"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(66)) goto parse_custom;
        break;
      }

      // optional .google.api.CustomHttpPattern custom = 8;
      case 8: {
        if (tag == 66) {
         parse_custom:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_custom()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(90)) goto parse_additional_bindings;
        break;
      }

      // repeated .google.api.HttpRule additional_bindings = 11;
      case 11: {
        if (tag == 90) {
         parse_additional_bindings:
          DO_(input->IncrementRecursionDepth());
         parse_loop_additional_bindings:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_additional_bindings()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(90)) goto parse_loop_additional_bindings;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:google.api.HttpRule)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:google.api.HttpRule)
  return false;
#undef DO_
}

void HttpRule::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:google.api.HttpRule)
  // optional string selector = 1;
  if (this->selector().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->selector().data(), this->selector().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.api.HttpRule.selector");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->selector(), output);
  }

  // optional string get = 2;
  if (has_get()) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->get().data(), this->get().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.api.HttpRule.get");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->get(), output);
  }

  // optional string put = 3;
  if (has_put()) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->put().data(), this->put().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.api.HttpRule.put");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->put(), output);
  }

  // optional string post = 4;
  if (has_post()) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->post().data(), this->post().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.api.HttpRule.post");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->post(), output);
  }

  // optional string delete = 5;
  if (has_delete_()) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->delete_().data(), this->delete_().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.api.HttpRule.delete");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->delete_(), output);
  }

  // optional string patch = 6;
  if (has_patch()) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->patch().data(), this->patch().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.api.HttpRule.patch");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->patch(), output);
  }

  // optional string body = 7;
  if (this->body().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->body().data(), this->body().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.api.HttpRule.body");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      7, this->body(), output);
  }

  // optional .google.api.CustomHttpPattern custom = 8;
  if (has_custom()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      8, *pattern_.custom_, output);
  }

  // repeated .google.api.HttpRule additional_bindings = 11;
  for (unsigned int i = 0, n = this->additional_bindings_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      11, this->additional_bindings(i), output);
  }

  // @@protoc_insertion_point(serialize_end:google.api.HttpRule)
}

::google::protobuf::uint8* HttpRule::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:google.api.HttpRule)
  // optional string selector = 1;
  if (this->selector().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->selector().data(), this->selector().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.api.HttpRule.selector");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->selector(), target);
  }

  // optional string get = 2;
  if (has_get()) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->get().data(), this->get().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.api.HttpRule.get");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->get(), target);
  }

  // optional string put = 3;
  if (has_put()) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->put().data(), this->put().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.api.HttpRule.put");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->put(), target);
  }

  // optional string post = 4;
  if (has_post()) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->post().data(), this->post().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.api.HttpRule.post");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->post(), target);
  }

  // optional string delete = 5;
  if (has_delete_()) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->delete_().data(), this->delete_().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.api.HttpRule.delete");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->delete_(), target);
  }

  // optional string patch = 6;
  if (has_patch()) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->patch().data(), this->patch().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.api.HttpRule.patch");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->patch(), target);
  }

  // optional string body = 7;
  if (this->body().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->body().data(), this->body().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.api.HttpRule.body");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        7, this->body(), target);
  }

  // optional .google.api.CustomHttpPattern custom = 8;
  if (has_custom()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        8, *pattern_.custom_, false, target);
  }

  // repeated .google.api.HttpRule additional_bindings = 11;
  for (unsigned int i = 0, n = this->additional_bindings_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        11, this->additional_bindings(i), false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:google.api.HttpRule)
  return target;
}

int HttpRule::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:google.api.HttpRule)
  int total_size = 0;

  // optional string selector = 1;
  if (this->selector().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->selector());
  }

  // optional string body = 7;
  if (this->body().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->body());
  }

  // repeated .google.api.HttpRule additional_bindings = 11;
  total_size += 1 * this->additional_bindings_size();
  for (int i = 0; i < this->additional_bindings_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->additional_bindings(i));
  }

  switch (pattern_case()) {
    // optional string get = 2;
    case kGet: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->get());
      break;
    }
    // optional string put = 3;
    case kPut: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->put());
      break;
    }
    // optional string post = 4;
    case kPost: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->post());
      break;
    }
    // optional string delete = 5;
    case kDelete: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->delete_());
      break;
    }
    // optional string patch = 6;
    case kPatch: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->patch());
      break;
    }
    // optional .google.api.CustomHttpPattern custom = 8;
    case kCustom: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *pattern_.custom_);
      break;
    }
    case PATTERN_NOT_SET: {
      break;
    }
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void HttpRule::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:google.api.HttpRule)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const HttpRule* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const HttpRule>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:google.api.HttpRule)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:google.api.HttpRule)
    MergeFrom(*source);
  }
}

void HttpRule::MergeFrom(const HttpRule& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:google.api.HttpRule)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  additional_bindings_.MergeFrom(from.additional_bindings_);
  switch (from.pattern_case()) {
    case kGet: {
      set_get(from.get());
      break;
    }
    case kPut: {
      set_put(from.put());
      break;
    }
    case kPost: {
      set_post(from.post());
      break;
    }
    case kDelete: {
      set_delete_(from.delete_());
      break;
    }
    case kPatch: {
      set_patch(from.patch());
      break;
    }
    case kCustom: {
      mutable_custom()->::google::api::CustomHttpPattern::MergeFrom(from.custom());
      break;
    }
    case PATTERN_NOT_SET: {
      break;
    }
  }
  if (from.selector().size() > 0) {
    set_selector(from.selector());
  }
  if (from.body().size() > 0) {
    set_body(from.body());
  }
}

void HttpRule::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:google.api.HttpRule)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void HttpRule::CopyFrom(const HttpRule& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.api.HttpRule)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HttpRule::IsInitialized() const {

  return true;
}

void HttpRule::Swap(HttpRule* other) {
  if (other == this) return;
  if (GetArenaNoVirtual() == other->GetArenaNoVirtual()) {
    InternalSwap(other);
  } else {
    HttpRule temp;
    temp.MergeFrom(*this);
    CopyFrom(*other);
    other->CopyFrom(temp);
  }
}
void HttpRule::UnsafeArenaSwap(HttpRule* other) {
  if (other == this) return;
  GOOGLE_DCHECK(GetArenaNoVirtual() == other->GetArenaNoVirtual());
  InternalSwap(other);
}
void HttpRule::InternalSwap(HttpRule* other) {
  selector_.Swap(&other->selector_);
  body_.Swap(&other->body_);
  additional_bindings_.UnsafeArenaSwap(&other->additional_bindings_);
  std::swap(pattern_, other->pattern_);
  std::swap(_oneof_case_[0], other->_oneof_case_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata HttpRule::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = HttpRule_descriptor_;
  metadata.reflection = HttpRule_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// HttpRule

// optional string selector = 1;
void HttpRule::clear_selector() {
  selector_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
 const ::std::string& HttpRule::selector() const {
  // @@protoc_insertion_point(field_get:google.api.HttpRule.selector)
  return selector_.Get(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void HttpRule::set_selector(const ::std::string& value) {
  
  selector_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set:google.api.HttpRule.selector)
}
 void HttpRule::set_selector(const char* value) {
  
  selector_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_char:google.api.HttpRule.selector)
}
 void HttpRule::set_selector(const char* value,
    size_t size) {
  
  selector_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_pointer:google.api.HttpRule.selector)
}
 ::std::string* HttpRule::mutable_selector() {
  
  // @@protoc_insertion_point(field_mutable:google.api.HttpRule.selector)
  return selector_.Mutable(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
 ::std::string* HttpRule::release_selector() {
  // @@protoc_insertion_point(field_release:google.api.HttpRule.selector)
  
  return selector_.Release(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
 ::std::string* HttpRule::unsafe_arena_release_selector() {
  // @@protoc_insertion_point(field_unsafe_arena_release:google.api.HttpRule.selector)
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  
  return selector_.UnsafeArenaRelease(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      GetArenaNoVirtual());
}
 void HttpRule::set_allocated_selector(::std::string* selector) {
  if (selector != NULL) {
    
  } else {
    
  }
  selector_.SetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), selector,
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:google.api.HttpRule.selector)
}
 void HttpRule::unsafe_arena_set_allocated_selector(
    ::std::string* selector) {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (selector != NULL) {
    
  } else {
    
  }
  selector_.UnsafeArenaSetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      selector, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:google.api.HttpRule.selector)
}

// optional string get = 2;
bool HttpRule::has_get() const {
  return pattern_case() == kGet;
}
void HttpRule::set_has_get() {
  _oneof_case_[0] = kGet;
}
void HttpRule::clear_get() {
  if (has_get()) {
    pattern_.get_.Destroy(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
        GetArenaNoVirtual());
    clear_has_pattern();
  }
}
 const ::std::string& HttpRule::get() const {
  // @@protoc_insertion_point(field_get:google.api.HttpRule.get)
  if (has_get()) {
    return pattern_.get_.Get(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  return *&::google::protobuf::internal::GetEmptyStringAlreadyInited();
}
 void HttpRule::set_get(const ::std::string& value) {
  if (!has_get()) {
    clear_pattern();
    set_has_get();
    pattern_.get_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  pattern_.get_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value,
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set:google.api.HttpRule.get)
}
 void HttpRule::set_get(const char* value) {
  if (!has_get()) {
    clear_pattern();
    set_has_get();
    pattern_.get_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  pattern_.get_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(value), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_char:google.api.HttpRule.get)
}
 void HttpRule::set_get(const char* value,
                             size_t size) {
  if (!has_get()) {
    clear_pattern();
    set_has_get();
    pattern_.get_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  pattern_.get_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size),
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_pointer:google.api.HttpRule.get)
}
 ::std::string* HttpRule::mutable_get() {
  if (!has_get()) {
    clear_pattern();
    set_has_get();
    pattern_.get_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  return pattern_.get_.Mutable(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_mutable:google.api.HttpRule.get)
}
 ::std::string* HttpRule::release_get() {
  // @@protoc_insertion_point(field_release:google.api.HttpRule.get)
  if (has_get()) {
    clear_has_pattern();
    return pattern_.get_.Release(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
        GetArenaNoVirtual());
  } else {
    return NULL;
  }
}
 ::std::string* HttpRule::unsafe_arena_release_get() {
  // @@protoc_insertion_point(field_unsafe_arena_release:google.api.HttpRule.get)
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (has_get()) {
    clear_has_pattern();
    return pattern_.get_.UnsafeArenaRelease(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
  } else {
    return NULL;
  }
}
 void HttpRule::set_allocated_get(::std::string* get) {
  if (!has_get()) {
    pattern_.get_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  clear_pattern();
  if (get != NULL) {
    set_has_get();
    pattern_.get_.SetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), get,
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_set_allocated:google.api.HttpRule.get)
}
 void HttpRule::unsafe_arena_set_allocated_get(::std::string* get) {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (!has_get()) {
    pattern_.get_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  clear_pattern();
  if (get) {
    set_has_get();
    pattern_.get_.UnsafeArenaSetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), get, GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:google.api.HttpRule.get)
}

// optional string put = 3;
bool HttpRule::has_put() const {
  return pattern_case() == kPut;
}
void HttpRule::set_has_put() {
  _oneof_case_[0] = kPut;
}
void HttpRule::clear_put() {
  if (has_put()) {
    pattern_.put_.Destroy(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
        GetArenaNoVirtual());
    clear_has_pattern();
  }
}
 const ::std::string& HttpRule::put() const {
  // @@protoc_insertion_point(field_get:google.api.HttpRule.put)
  if (has_put()) {
    return pattern_.put_.Get(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  return *&::google::protobuf::internal::GetEmptyStringAlreadyInited();
}
 void HttpRule::set_put(const ::std::string& value) {
  if (!has_put()) {
    clear_pattern();
    set_has_put();
    pattern_.put_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  pattern_.put_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value,
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set:google.api.HttpRule.put)
}
 void HttpRule::set_put(const char* value) {
  if (!has_put()) {
    clear_pattern();
    set_has_put();
    pattern_.put_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  pattern_.put_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(value), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_char:google.api.HttpRule.put)
}
 void HttpRule::set_put(const char* value,
                             size_t size) {
  if (!has_put()) {
    clear_pattern();
    set_has_put();
    pattern_.put_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  pattern_.put_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size),
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_pointer:google.api.HttpRule.put)
}
 ::std::string* HttpRule::mutable_put() {
  if (!has_put()) {
    clear_pattern();
    set_has_put();
    pattern_.put_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  return pattern_.put_.Mutable(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_mutable:google.api.HttpRule.put)
}
 ::std::string* HttpRule::release_put() {
  // @@protoc_insertion_point(field_release:google.api.HttpRule.put)
  if (has_put()) {
    clear_has_pattern();
    return pattern_.put_.Release(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
        GetArenaNoVirtual());
  } else {
    return NULL;
  }
}
 ::std::string* HttpRule::unsafe_arena_release_put() {
  // @@protoc_insertion_point(field_unsafe_arena_release:google.api.HttpRule.put)
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (has_put()) {
    clear_has_pattern();
    return pattern_.put_.UnsafeArenaRelease(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
  } else {
    return NULL;
  }
}
 void HttpRule::set_allocated_put(::std::string* put) {
  if (!has_put()) {
    pattern_.put_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  clear_pattern();
  if (put != NULL) {
    set_has_put();
    pattern_.put_.SetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), put,
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_set_allocated:google.api.HttpRule.put)
}
 void HttpRule::unsafe_arena_set_allocated_put(::std::string* put) {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (!has_put()) {
    pattern_.put_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  clear_pattern();
  if (put) {
    set_has_put();
    pattern_.put_.UnsafeArenaSetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), put, GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:google.api.HttpRule.put)
}

// optional string post = 4;
bool HttpRule::has_post() const {
  return pattern_case() == kPost;
}
void HttpRule::set_has_post() {
  _oneof_case_[0] = kPost;
}
void HttpRule::clear_post() {
  if (has_post()) {
    pattern_.post_.Destroy(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
        GetArenaNoVirtual());
    clear_has_pattern();
  }
}
 const ::std::string& HttpRule::post() const {
  // @@protoc_insertion_point(field_get:google.api.HttpRule.post)
  if (has_post()) {
    return pattern_.post_.Get(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  return *&::google::protobuf::internal::GetEmptyStringAlreadyInited();
}
 void HttpRule::set_post(const ::std::string& value) {
  if (!has_post()) {
    clear_pattern();
    set_has_post();
    pattern_.post_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  pattern_.post_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value,
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set:google.api.HttpRule.post)
}
 void HttpRule::set_post(const char* value) {
  if (!has_post()) {
    clear_pattern();
    set_has_post();
    pattern_.post_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  pattern_.post_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(value), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_char:google.api.HttpRule.post)
}
 void HttpRule::set_post(const char* value,
                             size_t size) {
  if (!has_post()) {
    clear_pattern();
    set_has_post();
    pattern_.post_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  pattern_.post_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size),
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_pointer:google.api.HttpRule.post)
}
 ::std::string* HttpRule::mutable_post() {
  if (!has_post()) {
    clear_pattern();
    set_has_post();
    pattern_.post_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  return pattern_.post_.Mutable(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_mutable:google.api.HttpRule.post)
}
 ::std::string* HttpRule::release_post() {
  // @@protoc_insertion_point(field_release:google.api.HttpRule.post)
  if (has_post()) {
    clear_has_pattern();
    return pattern_.post_.Release(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
        GetArenaNoVirtual());
  } else {
    return NULL;
  }
}
 ::std::string* HttpRule::unsafe_arena_release_post() {
  // @@protoc_insertion_point(field_unsafe_arena_release:google.api.HttpRule.post)
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (has_post()) {
    clear_has_pattern();
    return pattern_.post_.UnsafeArenaRelease(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
  } else {
    return NULL;
  }
}
 void HttpRule::set_allocated_post(::std::string* post) {
  if (!has_post()) {
    pattern_.post_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  clear_pattern();
  if (post != NULL) {
    set_has_post();
    pattern_.post_.SetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), post,
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_set_allocated:google.api.HttpRule.post)
}
 void HttpRule::unsafe_arena_set_allocated_post(::std::string* post) {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (!has_post()) {
    pattern_.post_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  clear_pattern();
  if (post) {
    set_has_post();
    pattern_.post_.UnsafeArenaSetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), post, GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:google.api.HttpRule.post)
}

// optional string delete = 5;
bool HttpRule::has_delete_() const {
  return pattern_case() == kDelete;
}
void HttpRule::set_has_delete_() {
  _oneof_case_[0] = kDelete;
}
void HttpRule::clear_delete_() {
  if (has_delete_()) {
    pattern_.delete__.Destroy(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
        GetArenaNoVirtual());
    clear_has_pattern();
  }
}
 const ::std::string& HttpRule::delete_() const {
  // @@protoc_insertion_point(field_get:google.api.HttpRule.delete)
  if (has_delete_()) {
    return pattern_.delete__.Get(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  return *&::google::protobuf::internal::GetEmptyStringAlreadyInited();
}
 void HttpRule::set_delete_(const ::std::string& value) {
  if (!has_delete_()) {
    clear_pattern();
    set_has_delete_();
    pattern_.delete__.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  pattern_.delete__.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value,
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set:google.api.HttpRule.delete)
}
 void HttpRule::set_delete_(const char* value) {
  if (!has_delete_()) {
    clear_pattern();
    set_has_delete_();
    pattern_.delete__.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  pattern_.delete__.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(value), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_char:google.api.HttpRule.delete)
}
 void HttpRule::set_delete_(const char* value,
                             size_t size) {
  if (!has_delete_()) {
    clear_pattern();
    set_has_delete_();
    pattern_.delete__.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  pattern_.delete__.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size),
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_pointer:google.api.HttpRule.delete)
}
 ::std::string* HttpRule::mutable_delete_() {
  if (!has_delete_()) {
    clear_pattern();
    set_has_delete_();
    pattern_.delete__.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  return pattern_.delete__.Mutable(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_mutable:google.api.HttpRule.delete)
}
 ::std::string* HttpRule::release_delete_() {
  // @@protoc_insertion_point(field_release:google.api.HttpRule.delete)
  if (has_delete_()) {
    clear_has_pattern();
    return pattern_.delete__.Release(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
        GetArenaNoVirtual());
  } else {
    return NULL;
  }
}
 ::std::string* HttpRule::unsafe_arena_release_delete_() {
  // @@protoc_insertion_point(field_unsafe_arena_release:google.api.HttpRule.delete)
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (has_delete_()) {
    clear_has_pattern();
    return pattern_.delete__.UnsafeArenaRelease(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
  } else {
    return NULL;
  }
}
 void HttpRule::set_allocated_delete_(::std::string* delete_) {
  if (!has_delete_()) {
    pattern_.delete__.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  clear_pattern();
  if (delete_ != NULL) {
    set_has_delete_();
    pattern_.delete__.SetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), delete_,
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_set_allocated:google.api.HttpRule.delete)
}
 void HttpRule::unsafe_arena_set_allocated_delete_(::std::string* delete_) {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (!has_delete_()) {
    pattern_.delete__.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  clear_pattern();
  if (delete_) {
    set_has_delete_();
    pattern_.delete__.UnsafeArenaSetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), delete_, GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:google.api.HttpRule.delete)
}

// optional string patch = 6;
bool HttpRule::has_patch() const {
  return pattern_case() == kPatch;
}
void HttpRule::set_has_patch() {
  _oneof_case_[0] = kPatch;
}
void HttpRule::clear_patch() {
  if (has_patch()) {
    pattern_.patch_.Destroy(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
        GetArenaNoVirtual());
    clear_has_pattern();
  }
}
 const ::std::string& HttpRule::patch() const {
  // @@protoc_insertion_point(field_get:google.api.HttpRule.patch)
  if (has_patch()) {
    return pattern_.patch_.Get(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  return *&::google::protobuf::internal::GetEmptyStringAlreadyInited();
}
 void HttpRule::set_patch(const ::std::string& value) {
  if (!has_patch()) {
    clear_pattern();
    set_has_patch();
    pattern_.patch_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  pattern_.patch_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value,
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set:google.api.HttpRule.patch)
}
 void HttpRule::set_patch(const char* value) {
  if (!has_patch()) {
    clear_pattern();
    set_has_patch();
    pattern_.patch_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  pattern_.patch_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(value), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_char:google.api.HttpRule.patch)
}
 void HttpRule::set_patch(const char* value,
                             size_t size) {
  if (!has_patch()) {
    clear_pattern();
    set_has_patch();
    pattern_.patch_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  pattern_.patch_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size),
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_pointer:google.api.HttpRule.patch)
}
 ::std::string* HttpRule::mutable_patch() {
  if (!has_patch()) {
    clear_pattern();
    set_has_patch();
    pattern_.patch_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  return pattern_.patch_.Mutable(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_mutable:google.api.HttpRule.patch)
}
 ::std::string* HttpRule::release_patch() {
  // @@protoc_insertion_point(field_release:google.api.HttpRule.patch)
  if (has_patch()) {
    clear_has_pattern();
    return pattern_.patch_.Release(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
        GetArenaNoVirtual());
  } else {
    return NULL;
  }
}
 ::std::string* HttpRule::unsafe_arena_release_patch() {
  // @@protoc_insertion_point(field_unsafe_arena_release:google.api.HttpRule.patch)
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (has_patch()) {
    clear_has_pattern();
    return pattern_.patch_.UnsafeArenaRelease(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
  } else {
    return NULL;
  }
}
 void HttpRule::set_allocated_patch(::std::string* patch) {
  if (!has_patch()) {
    pattern_.patch_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  clear_pattern();
  if (patch != NULL) {
    set_has_patch();
    pattern_.patch_.SetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), patch,
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_set_allocated:google.api.HttpRule.patch)
}
 void HttpRule::unsafe_arena_set_allocated_patch(::std::string* patch) {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (!has_patch()) {
    pattern_.patch_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  clear_pattern();
  if (patch) {
    set_has_patch();
    pattern_.patch_.UnsafeArenaSetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), patch, GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:google.api.HttpRule.patch)
}

// optional .google.api.CustomHttpPattern custom = 8;
bool HttpRule::has_custom() const {
  return pattern_case() == kCustom;
}
void HttpRule::set_has_custom() {
  _oneof_case_[0] = kCustom;
}
void HttpRule::clear_custom() {
  if (has_custom()) {
    if (GetArenaNoVirtual() == NULL) {
      delete pattern_.custom_;
    }
    clear_has_pattern();
  }
}
 const ::google::api::CustomHttpPattern& HttpRule::custom() const {
  // @@protoc_insertion_point(field_get:google.api.HttpRule.custom)
  return has_custom()
      ? *pattern_.custom_
      : ::google::api::CustomHttpPattern::default_instance();
}
::google::api::CustomHttpPattern* HttpRule::mutable_custom() {
  if (!has_custom()) {
    clear_pattern();
    set_has_custom();
    pattern_.custom_ = 
      ::google::protobuf::Arena::CreateMessage< ::google::api::CustomHttpPattern >(
      GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:google.api.HttpRule.custom)
  return pattern_.custom_;
}
::google::api::CustomHttpPattern* HttpRule::release_custom() {
  // @@protoc_insertion_point(field_release:google.api.HttpRule.custom)
  if (has_custom()) {
    clear_has_pattern();
    if (GetArenaNoVirtual() != NULL) {
      ::google::api::CustomHttpPattern* temp = new ::google::api::CustomHttpPattern;
      temp->MergeFrom(*pattern_.custom_);
      pattern_.custom_ = NULL;
      return temp;
    } else {
      ::google::api::CustomHttpPattern* temp = pattern_.custom_;
      pattern_.custom_ = NULL;
      return temp;
    }
  } else {
    return NULL;
  }
}
void HttpRule::set_allocated_custom(::google::api::CustomHttpPattern* custom) {
  clear_pattern();
  if (custom) {
    if (GetArenaNoVirtual() != NULL &&
        ::google::protobuf::Arena::GetArena(custom) == NULL) {
      GetArenaNoVirtual()->Own(custom);
    } else if (GetArenaNoVirtual() !=
               ::google::protobuf::Arena::GetArena(custom)) {
      ::google::api::CustomHttpPattern* new_custom = 
          ::google::protobuf::Arena::CreateMessage< ::google::api::CustomHttpPattern >(
          GetArenaNoVirtual());
      new_custom->CopyFrom(*custom);
      custom = new_custom;
    }
    set_has_custom();
    pattern_.custom_ = custom;
  }
  // @@protoc_insertion_point(field_set_allocated:google.api.HttpRule.custom)
}
 ::google::api::CustomHttpPattern* HttpRule::unsafe_arena_release_custom() {
  // @@protoc_insertion_point(field_unsafe_arena_release:google.api.HttpRule.custom)
  if (has_custom()) {
    clear_has_pattern();
    ::google::api::CustomHttpPattern* temp = pattern_.custom_;
    pattern_.custom_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
 void HttpRule::unsafe_arena_set_allocated_custom(::google::api::CustomHttpPattern* custom) {
  clear_pattern();
  if (custom) {
    set_has_custom();
    pattern_.custom_ = custom;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:google.api.HttpRule.custom)
}

// optional string body = 7;
void HttpRule::clear_body() {
  body_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
 const ::std::string& HttpRule::body() const {
  // @@protoc_insertion_point(field_get:google.api.HttpRule.body)
  return body_.Get(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void HttpRule::set_body(const ::std::string& value) {
  
  body_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set:google.api.HttpRule.body)
}
 void HttpRule::set_body(const char* value) {
  
  body_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_char:google.api.HttpRule.body)
}
 void HttpRule::set_body(const char* value,
    size_t size) {
  
  body_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_pointer:google.api.HttpRule.body)
}
 ::std::string* HttpRule::mutable_body() {
  
  // @@protoc_insertion_point(field_mutable:google.api.HttpRule.body)
  return body_.Mutable(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
 ::std::string* HttpRule::release_body() {
  // @@protoc_insertion_point(field_release:google.api.HttpRule.body)
  
  return body_.Release(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
 ::std::string* HttpRule::unsafe_arena_release_body() {
  // @@protoc_insertion_point(field_unsafe_arena_release:google.api.HttpRule.body)
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  
  return body_.UnsafeArenaRelease(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      GetArenaNoVirtual());
}
 void HttpRule::set_allocated_body(::std::string* body) {
  if (body != NULL) {
    
  } else {
    
  }
  body_.SetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), body,
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:google.api.HttpRule.body)
}
 void HttpRule::unsafe_arena_set_allocated_body(
    ::std::string* body) {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (body != NULL) {
    
  } else {
    
  }
  body_.UnsafeArenaSetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      body, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:google.api.HttpRule.body)
}

// repeated .google.api.HttpRule additional_bindings = 11;
int HttpRule::additional_bindings_size() const {
  return additional_bindings_.size();
}
void HttpRule::clear_additional_bindings() {
  additional_bindings_.Clear();
}
const ::google::api::HttpRule& HttpRule::additional_bindings(int index) const {
  // @@protoc_insertion_point(field_get:google.api.HttpRule.additional_bindings)
  return additional_bindings_.Get(index);
}
::google::api::HttpRule* HttpRule::mutable_additional_bindings(int index) {
  // @@protoc_insertion_point(field_mutable:google.api.HttpRule.additional_bindings)
  return additional_bindings_.Mutable(index);
}
::google::api::HttpRule* HttpRule::add_additional_bindings() {
  // @@protoc_insertion_point(field_add:google.api.HttpRule.additional_bindings)
  return additional_bindings_.Add();
}
::google::protobuf::RepeatedPtrField< ::google::api::HttpRule >*
HttpRule::mutable_additional_bindings() {
  // @@protoc_insertion_point(field_mutable_list:google.api.HttpRule.additional_bindings)
  return &additional_bindings_;
}
const ::google::protobuf::RepeatedPtrField< ::google::api::HttpRule >&
HttpRule::additional_bindings() const {
  // @@protoc_insertion_point(field_list:google.api.HttpRule.additional_bindings)
  return additional_bindings_;
}

bool HttpRule::has_pattern() const {
  return pattern_case() != PATTERN_NOT_SET;
}
void HttpRule::clear_has_pattern() {
  _oneof_case_[0] = PATTERN_NOT_SET;
}
HttpRule::PatternCase HttpRule::pattern_case() const {
  return HttpRule::PatternCase(_oneof_case_[0]);
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CustomHttpPattern::kKindFieldNumber;
const int CustomHttpPattern::kPathFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CustomHttpPattern::CustomHttpPattern()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:google.api.CustomHttpPattern)
}

CustomHttpPattern::CustomHttpPattern(::google::protobuf::Arena* arena)
  : ::google::protobuf::Message(),
  _internal_metadata_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:google.api.CustomHttpPattern)
}

void CustomHttpPattern::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

CustomHttpPattern::CustomHttpPattern(const CustomHttpPattern& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:google.api.CustomHttpPattern)
}

void CustomHttpPattern::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  kind_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  path_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

CustomHttpPattern::~CustomHttpPattern() {
  // @@protoc_insertion_point(destructor:google.api.CustomHttpPattern)
  SharedDtor();
}

void CustomHttpPattern::SharedDtor() {
  if (GetArenaNoVirtual() != NULL) {
    return;
  }

  kind_.Destroy(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
  path_.Destroy(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
  if (this != default_instance_) {
  }
}

void CustomHttpPattern::ArenaDtor(void* object) {
  CustomHttpPattern* _this = reinterpret_cast< CustomHttpPattern* >(object);
  (void)_this;
}
void CustomHttpPattern::RegisterArenaDtor(::google::protobuf::Arena* arena) {
}
void CustomHttpPattern::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CustomHttpPattern::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CustomHttpPattern_descriptor_;
}

const CustomHttpPattern& CustomHttpPattern::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_google_2fapi_2fhttp_2eproto();
  return *default_instance_;
}

CustomHttpPattern* CustomHttpPattern::default_instance_ = NULL;

CustomHttpPattern* CustomHttpPattern::New(::google::protobuf::Arena* arena) const {
  return ::google::protobuf::Arena::CreateMessage<CustomHttpPattern>(arena);
}

void CustomHttpPattern::Clear() {
// @@protoc_insertion_point(message_clear_start:google.api.CustomHttpPattern)
  kind_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
  path_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}

bool CustomHttpPattern::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:google.api.CustomHttpPattern)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string kind = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_kind()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->kind().data(), this->kind().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.api.CustomHttpPattern.kind"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_path;
        break;
      }

      // optional string path = 2;
      case 2: {
        if (tag == 18) {
         parse_path:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_path()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->path().data(), this->path().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.api.CustomHttpPattern.path"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:google.api.CustomHttpPattern)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:google.api.CustomHttpPattern)
  return false;
#undef DO_
}

void CustomHttpPattern::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:google.api.CustomHttpPattern)
  // optional string kind = 1;
  if (this->kind().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->kind().data(), this->kind().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.api.CustomHttpPattern.kind");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->kind(), output);
  }

  // optional string path = 2;
  if (this->path().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->path().data(), this->path().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.api.CustomHttpPattern.path");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->path(), output);
  }

  // @@protoc_insertion_point(serialize_end:google.api.CustomHttpPattern)
}

::google::protobuf::uint8* CustomHttpPattern::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:google.api.CustomHttpPattern)
  // optional string kind = 1;
  if (this->kind().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->kind().data(), this->kind().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.api.CustomHttpPattern.kind");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->kind(), target);
  }

  // optional string path = 2;
  if (this->path().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->path().data(), this->path().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.api.CustomHttpPattern.path");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->path(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:google.api.CustomHttpPattern)
  return target;
}

int CustomHttpPattern::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:google.api.CustomHttpPattern)
  int total_size = 0;

  // optional string kind = 1;
  if (this->kind().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->kind());
  }

  // optional string path = 2;
  if (this->path().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->path());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CustomHttpPattern::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:google.api.CustomHttpPattern)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const CustomHttpPattern* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const CustomHttpPattern>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:google.api.CustomHttpPattern)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:google.api.CustomHttpPattern)
    MergeFrom(*source);
  }
}

void CustomHttpPattern::MergeFrom(const CustomHttpPattern& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:google.api.CustomHttpPattern)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.kind().size() > 0) {
    set_kind(from.kind());
  }
  if (from.path().size() > 0) {
    set_path(from.path());
  }
}

void CustomHttpPattern::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:google.api.CustomHttpPattern)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CustomHttpPattern::CopyFrom(const CustomHttpPattern& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.api.CustomHttpPattern)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CustomHttpPattern::IsInitialized() const {

  return true;
}

void CustomHttpPattern::Swap(CustomHttpPattern* other) {
  if (other == this) return;
  if (GetArenaNoVirtual() == other->GetArenaNoVirtual()) {
    InternalSwap(other);
  } else {
    CustomHttpPattern temp;
    temp.MergeFrom(*this);
    CopyFrom(*other);
    other->CopyFrom(temp);
  }
}
void CustomHttpPattern::UnsafeArenaSwap(CustomHttpPattern* other) {
  if (other == this) return;
  GOOGLE_DCHECK(GetArenaNoVirtual() == other->GetArenaNoVirtual());
  InternalSwap(other);
}
void CustomHttpPattern::InternalSwap(CustomHttpPattern* other) {
  kind_.Swap(&other->kind_);
  path_.Swap(&other->path_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CustomHttpPattern::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CustomHttpPattern_descriptor_;
  metadata.reflection = CustomHttpPattern_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CustomHttpPattern

// optional string kind = 1;
void CustomHttpPattern::clear_kind() {
  kind_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
 const ::std::string& CustomHttpPattern::kind() const {
  // @@protoc_insertion_point(field_get:google.api.CustomHttpPattern.kind)
  return kind_.Get(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CustomHttpPattern::set_kind(const ::std::string& value) {
  
  kind_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set:google.api.CustomHttpPattern.kind)
}
 void CustomHttpPattern::set_kind(const char* value) {
  
  kind_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_char:google.api.CustomHttpPattern.kind)
}
 void CustomHttpPattern::set_kind(const char* value,
    size_t size) {
  
  kind_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_pointer:google.api.CustomHttpPattern.kind)
}
 ::std::string* CustomHttpPattern::mutable_kind() {
  
  // @@protoc_insertion_point(field_mutable:google.api.CustomHttpPattern.kind)
  return kind_.Mutable(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
 ::std::string* CustomHttpPattern::release_kind() {
  // @@protoc_insertion_point(field_release:google.api.CustomHttpPattern.kind)
  
  return kind_.Release(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
 ::std::string* CustomHttpPattern::unsafe_arena_release_kind() {
  // @@protoc_insertion_point(field_unsafe_arena_release:google.api.CustomHttpPattern.kind)
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  
  return kind_.UnsafeArenaRelease(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      GetArenaNoVirtual());
}
 void CustomHttpPattern::set_allocated_kind(::std::string* kind) {
  if (kind != NULL) {
    
  } else {
    
  }
  kind_.SetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), kind,
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:google.api.CustomHttpPattern.kind)
}
 void CustomHttpPattern::unsafe_arena_set_allocated_kind(
    ::std::string* kind) {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (kind != NULL) {
    
  } else {
    
  }
  kind_.UnsafeArenaSetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      kind, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:google.api.CustomHttpPattern.kind)
}

// optional string path = 2;
void CustomHttpPattern::clear_path() {
  path_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
 const ::std::string& CustomHttpPattern::path() const {
  // @@protoc_insertion_point(field_get:google.api.CustomHttpPattern.path)
  return path_.Get(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CustomHttpPattern::set_path(const ::std::string& value) {
  
  path_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set:google.api.CustomHttpPattern.path)
}
 void CustomHttpPattern::set_path(const char* value) {
  
  path_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_char:google.api.CustomHttpPattern.path)
}
 void CustomHttpPattern::set_path(const char* value,
    size_t size) {
  
  path_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_pointer:google.api.CustomHttpPattern.path)
}
 ::std::string* CustomHttpPattern::mutable_path() {
  
  // @@protoc_insertion_point(field_mutable:google.api.CustomHttpPattern.path)
  return path_.Mutable(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
 ::std::string* CustomHttpPattern::release_path() {
  // @@protoc_insertion_point(field_release:google.api.CustomHttpPattern.path)
  
  return path_.Release(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
 ::std::string* CustomHttpPattern::unsafe_arena_release_path() {
  // @@protoc_insertion_point(field_unsafe_arena_release:google.api.CustomHttpPattern.path)
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  
  return path_.UnsafeArenaRelease(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      GetArenaNoVirtual());
}
 void CustomHttpPattern::set_allocated_path(::std::string* path) {
  if (path != NULL) {
    
  } else {
    
  }
  path_.SetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), path,
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:google.api.CustomHttpPattern.path)
}
 void CustomHttpPattern::unsafe_arena_set_allocated_path(
    ::std::string* path) {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (path != NULL) {
    
  } else {
    
  }
  path_.UnsafeArenaSetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      path, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:google.api.CustomHttpPattern.path)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace api
}  // namespace google

// @@protoc_insertion_point(global_scope)
