
find_path(PPCONSUL_INCLUDE_DIR
  NAMES ppconsul/ppconsul.h
  PATHS ${PPCONSUL_INCLUDE_DIRS}
  DOC "Include directory for the ppconsul library."
)

find_library(PPCONSUL_LIBRARIES_PPCONSUL
  NAMES ppconsul
  PATHS ${PPCONSUL_LIBRARY_DIRS}
)
find_library(PPCONSUL_LIBRARIES_JSON11
  NAMES json11
  PATHS ${PPCONSUL_LIBRARY_DIRS}
)

if(PPCONSUL_INCLUDE_DIR AND PPCONSUL_LIBRARIES_PPCONSUL AND PPCONSUL_LIBRARIES_JSON11)
  set(PPCONSUL_LIBRARIES ${PPCONSUL_LIBRARIES_PPCONSUL} ${PPCONSUL_LIBRARIES_JSON11})
  set(PPCONSUL_FOUND TRUE)
endif()

